name: Nodejs Build template
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
        desription: 'The Nodejs version to use for the build'

jobs:
  build:
    run-on: ubuntu-lastest
    setp:
      - name: Checkout Code
        uses: actions/checkout@4
      - name: Set up Node.js ${{inputs.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
      - name: Install dependencies
        run: npm install